name: Daily Note
description: 日常记录、学习笔记、随手记
labels: ['note']
title: 'Note: '
body:
  - type: markdown
    attributes:
      value: 记录你的想法、学习内容或任何值得记下的东西。
  - type: input
    id: topic
    attributes:
      label: 主题/标签
      description: 简短描述这条记录的主题（可选）
      placeholder: 例如：React、读书笔记、灵感
    validations:
      required: false
  - type: textarea
    id: content
    attributes:
      label: 内容
      description: 写下你想记录的内容
      placeholder: |
        今天学到了什么？
        有什么想法？
        看到了什么有趣的东西？
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 参考链接
      description: 相关的文章、视频或其他资源链接（可选）
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: todo
    attributes:
      label: 待办/后续
      description: 需要进一步研究或完成的事项（可选）
      placeholder: |
        - [ ] 深入了解 xxx
        - [ ] 实践 xxx
    validations:
      required: false
